version: '3.8'

services:
  MeetSchedulerBot:
    image: openjdk:17-jdk-alpine
    container_name: MeetSchedulerBot
    restart: always
    ports:
      - "8081:8080"
    networks:
      - postgres-net
    volumes:
      - ./target/MeetSchedulerBot.jar:/app/MeetSchedulerBot.jar
    command: ["java", "-jar", "/app/MeetSchedulerBot.jar"]

networks:
  postgres-net:
    external: true
